export const dummyRecipes = [
	{
		id: "recipe_1",
		name: "Spaghetti Bolognese",
		instruction: "Cook pasta, make sauce, mix together.",
		type_of_cuisine: "Italian",
		nutrient_counts: "500 kcal",
		serve_hot_or_cold: "Hot",
		cooking_time: "30 mins",
		benefits: "Rich in protein",
		serve_for: "2 people",
		user_id: "user_1",
		ingredients: "Tomato, Onion, Ground Beef, Pasta",
	},
	{
		id: "recipe_2",
		name: "Grilled Chicken Salad",
		instruction: "Grill the chicken, mix with veggies.",
		type_of_cuisine: "American",
		nutrient_counts: "300 kcal",
		serve_hot_or_cold: "Cold",
		cooking_time: "20 mins",
		benefits: "High in protein, low in carbs",
		serve_for: "1 person",
		user_id: "user_2",
		ingredients: "Chicken Breast, Lettuce, Carrot, Olive Oil",
	},
	{
		id: "recipe_3",
		name: "Chicken Curry",
		instruction: "Cook chicken in curry sauce, serve with rice.",
		type_of_cuisine: "Indian",
		nutrient_counts: "600 kcal",
		serve_hot_or_cold: "Hot",
		cooking_time: "40 mins",
		benefits: "Good source of protein and spices",
		serve_for: "4 people",
		user_id: "user_3",
		ingredients: "Chicken, Curry Powder, Coconut Milk, Rice",
	},
	{
		id: "recipe_4",
		name: "Avocado Toast",
		instruction: "Toast bread, spread avocado, add seasoning.",
		type_of_cuisine: "Fusion",
		nutrient_counts: "250 kcal",
		serve_hot_or_cold: "Cold",
		cooking_time: "5 mins",
		benefits: "High in healthy fats",
		serve_for: "1 person",
		user_id: "user_4",
		ingredients: "Avocado, Bread, Olive Oil, Salt",
	},
	{
		id: "recipe_5",
		name: "Vegetable Stir Fry",
		instruction: "Stir-fry vegetables, serve with rice or noodles.",
		type_of_cuisine: "Asian",
		nutrient_counts: "400 kcal",
		serve_hot_or_cold: "Hot",
		cooking_time: "15 mins",
		benefits: "High in vitamins and fiber",
		serve_for: "3 people",
		user_id: "user_5",
		ingredients: "Bell Peppers, Carrot, Broccoli, Soy Sauce, Rice",
	},
];

export const dummyRecipePosts = [
	{
		id: "post_1",
		recipe_id: "recipe_1",
		user: {
			id: "user_1",
			firstName: "John",
			lastName: "Doe",
			userName: "johndoe123",
			email: "john.doe@example.com",
		},
		posted_at: "2024-09-16T12:00:00",
		recipe: {
			id: "recipe_1",
			name: "Spaghetti Bolognese",
			instruction: "Cook pasta, make sauce, mix together.",
			type_of_cuisine: "Italian",
			nutrient_counts: "500 kcal",
			serve_hot_or_cold: "Hot",
			cooking_time: "30 mins",
			benefits: "Rich in protein",
			serve_for: "2 people",
			user_id: "user_1",
			ingredients: "Tomato, Onion, Ground Beef, Pasta",
		},
		likes: [
			{
				id: "like_1",
				user_id: "user_2",
				post_id: "post_1",
				liked_at: "2024-09-17T10:00:00",
			},
			{
				id: "like_2",
				user_id: "user_3",
				post_id: "post_1",
				liked_at: "2024-09-18T09:30:00",
			},
		],
	},
	{
		id: "post_2",
		recipe_id: "recipe_2",
		user: {
			id: "user_2",
			firstName: "Jane",
			lastName: "Smith",
			userName: "janesmith321",
			email: "jane.smith@example.com",
		},
		posted_at: "2024-09-17T14:00:00",
		recipe: {
			id: "recipe_2",
			name: "Grilled Chicken Salad",
			instruction: "Grill the chicken, mix with veggies.",
			type_of_cuisine: "American",
			nutrient_counts: "300 kcal",
			serve_hot_or_cold: "Cold",
			cooking_time: "20 mins",
			benefits: "High in protein, low in carbs",
			serve_for: "1 person",
			user_id: "user_2",
			ingredients: "Chicken Breast, Lettuce, Carrot, Olive Oil",
		},
		likes: [
			{
				id: "like_3",
				user_id: "user_1",
				post_id: "post_2",
				liked_at: "2024-09-18T09:00:00",
			},
			{
				id: "like_4",
				user_id: "user_3",
				post_id: "post_2",
				liked_at: "2024-09-19T08:45:00",
			},
		],
	},
	{
		id: "post_3",
		recipe_id: "recipe_3",
		user: {
			id: "user_3",
			firstName: "Michael",
			lastName: "Johnson",
			userName: "michaelj789",
			email: "michael.johnson@example.com",
		},
		posted_at: "2024-09-18T16:30:00",
		recipe: {
			id: "recipe_3",
			name: "Chicken Curry",
			instruction: "Cook chicken in curry sauce, serve with rice.",
			type_of_cuisine: "Indian",
			nutrient_counts: "600 kcal",
			serve_hot_or_cold: "Hot",
			cooking_time: "40 mins",
			benefits: "Good source of protein and spices",
			serve_for: "4 people",
			user_id: "user_3",
			ingredients: "Chicken, Curry Powder, Coconut Milk, Rice",
		},
		likes: [
			{
				id: "like_5",
				user_id: "user_1",
				post_id: "post_3",
				liked_at: "2024-09-19T10:30:00",
			},
		],
	},
];
