export const seasonings = [
	{ key: "1", value: "Salt" },
	{ key: "2", value: "Black Pepper" },
	{ key: "3", value: "Paprika" },
	{ key: "4", value: "Garlic Powder" },
	{ key: "5", value: "Onion Powder" },
	{ key: "6", value: "Cayenne Pepper" },
	{ key: "7", value: "Cumin" },
	{ key: "8", value: "Chili Powder" },
	{ key: "9", value: "Turmeric" },
	{ key: "10", value: "Coriander" },
	{ key: "11", value: "Ground Mustard" },
	{ key: "12", value: "Cinnamon" },
	{ key: "13", value: "Nutmeg" },
	{ key: "14", value: "Cloves" },
	{ key: "15", value: "Ginger Powder" },
	{ key: "16", value: "Oregano" },
	{ key: "17", value: "Thyme" },
	{ key: "18", value: "Rosemary" },
	{ key: "19", value: "Basil" },
	{ key: "20", value: "Bay Leaves" },
	{ key: "21", value: "Parsley" },
	{ key: "22", value: "Dill" },
	{ key: "23", value: "Tarragon" },
	{ key: "24", value: "Fennel Seeds" },
	{ key: "25", value: "Star Anise" },
	{ key: "26", value: "Fenugreek" },
	{ key: "27", value: "Saffron" },
	{ key: "28", value: "Cardamom" },
	{ key: "29", value: "Allspice" },
	{ key: "30", value: "Curry Powder" },
	{ key: "31", value: "Italian Seasoning" },
	{ key: "32", value: "Herbes de Provence" },
	{ key: "33", value: "Smoked Paprika" },
	{ key: "34", value: "White Pepper" },
	{ key: "35", value: "Celery Salt" },
	{ key: "36", value: "Lemon Pepper" },
	{ key: "37", value: "Sumac" },
	{ key: "38", value: "Za'atar" },
	{ key: "39", value: "Sichuan Peppercorns" },
	{ key: "40", value: "Five-Spice Powder" },
	{ key: "41", value: "Chili Flakes" },
	{ key: "42", value: "Vanilla Bean" },
	{ key: "43", value: "Sesame Seeds" },
	{ key: "44", value: "Poppy Seeds" },
	{ key: "45", value: "Nigella Seeds" },
	{ key: "46", value: "Cumin Seeds" },
	{ key: "47", value: "Caraway Seeds" },
	{ key: "48", value: "Mustard Seeds" },
	{ key: "49", value: "Ground Cloves" },
	{ key: "50", value: "Tumeric" },
	{ key: "51", value: "Ground Mace" },
	{ key: "52", value: "Fenugreek Seeds" },
	{ key: "53", value: "Curry Leaves" },
	{ key: "54", value: "Galangal" },
	{ key: "55", value: "Garlic Salt" },
	{ key: "56", value: "Lime Zest" },
	{ key: "57", value: "Orange Zest" },
	{ key: "58", value: "Lavender" },
	{ key: "59", value: "Marjoram" },
	{ key: "60", value: "Sage" },
	{ key: "61", value: "Chervil" },
	{ key: "62", value: "Tamarind" },
	{ key: "63", value: "Mint" },
	{ key: "64", value: "Chives" },
	{ key: "65", value: "Curry Paste" },
	{ key: "66", value: "Lemongrass" },
	{ key: "67", value: "Cilantro" },
	{ key: "68", value: "Harissa" },
	{ key: "69", value: "Wasabi" },
	{ key: "70", value: "Horseradish" },
	{ key: "71", value: "Sichuan Chili Oil" },
	{ key: "72", value: "Basil Seeds" },
	{ key: "73", value: "Pink Salt" },
	{ key: "74", value: "Truffle Salt" },
	{ key: "75", value: "Dried Shrimp Paste" },
	{ key: "76", value: "Cacao Powder" },
	{ key: "77", value: "Togarashi" },
	{ key: "78", value: "Rose Petals" },
	{ key: "79", value: "Garlic Chives" },
	{ key: "80", value: "Ajwain" },
	{ key: "81", value: "Black Mustard Seeds" },
	{ key: "82", value: "Dry Mango Powder (Amchur)" },
	{ key: "83", value: "Mace" },
	{ key: "84", value: "Nigella Seeds (Kalonji)" },
	{ key: "85", value: "Juniper Berries" },
	{ key: "86", value: "Gooseberries" },
	{ key: "87", value: "Pomegranate Seeds" },
	{ key: "88", value: "Mahlab" },
	{ key: "89", value: "Baharat" },
	{ key: "90", value: "Urfa Biber" },
	{ key: "91", value: "Achiote" },
	{ key: "92", value: "Epazote" },
	{ key: "93", value: "Tzatziki Spice" },
	{ key: "94", value: "Kaffir Lime Leaves" },
	{ key: "95", value: "Barberries" },
	{ key: "96", value: "Berbere" },
	{ key: "97", value: "Kashmiri Chili Powder" },
	{ key: "98", value: "Dried Mint" },
	{ key: "99", value: "Ras El Hanout" },
	{ key: "100", value: "Pilpelchuma" },
	{ key: "101", value: "Persian Saffron" },
	{ key: "102", value: "Shiso Leaves" },
	{ key: "103", value: "Smoked Salt" },
	{ key: "104", value: "Asafoetida" },
	// Sweeteners
	{ key: "105", value: "Sugar" },
	{ key: "106", value: "Brown Sugar" },
	{ key: "107", value: "Honey" },
	{ key: "108", value: "Maple Syrup" },
	{ key: "109", value: "Agave Syrup" },
	{ key: "110", value: "Molasses" },
	{ key: "111", value: "Stevia" },
	{ key: "112", value: "Coconut Sugar" },
	{ key: "113", value: "Date Syrup" },
	{ key: "114", value: "Corn Syrup" },
	{ key: "115", value: "Palm Sugar" },

	// Sauces and Condiments
	{ key: "116", value: "Soy Sauce" },
	{ key: "117", value: "Tamari" },
	{ key: "118", value: "Worcestershire Sauce" },
	{ key: "119", value: "Oyster Sauce" },
	{ key: "120", value: "Fish Sauce" },
	{ key: "121", value: "Vinegar" },
	{ key: "122", value: "Apple Cider Vinegar" },
	{ key: "123", value: "Balsamic Vinegar" },
	{ key: "124", value: "Rice Vinegar" },
	{ key: "125", value: "Hot Sauce" },
	{ key: "126", value: "Ketchup" },
	{ key: "127", value: "Mustard" },
	{ key: "128", value: "BBQ Sauce" },
	{ key: "129", value: "Hoisin Sauce" },
	{ key: "130", value: "Sriracha" },
	{ key: "131", value: "Tahini" },
	{ key: "132", value: "Miso Paste" },
	{ key: "133", value: "Chili Sauce" },
	{ key: "134", value: "Sesame Oil" },
	{ key: "135", value: "Truffle Oil" },
	{ key: "136", value: "Teriyaki Sauce" },
	{ key: "137", value: "Chili Oil" },
	{ key: "138", value: "Ponzu" },
	{ key: "139", value: "Mirin" },
	{ key: "140", value: "Gochujang" },
	{ key: "141", value: "Aioli" },
	{ key: "142", value: "Ranch Dressing" },
	{ key: "143", value: "Tartar Sauce" },

	// Other Add-ins
	{ key: "144", value: "Cornstarch" },
	{ key: "145", value: "Arrowroot Powder" },
	{ key: "146", value: "Baking Powder" },
	{ key: "147", value: "Baking Soda" },
	{ key: "148", value: "Cream of Tartar" },
	{ key: "149", value: "Yeast" },
	{ key: "150", value: "Vegan Egg Substitute" },
	{ key: "151", value: "Gelatin" },
	{ key: "152", value: "Agar Agar" },
	{ key: "153", value: "Xanthan Gum" },
	{ key: "154", value: "Guar Gum" },
	{ key: "155", value: "Pectin" },
	{ key: "156", value: "Lecithin" },
	{ key: "157", value: "Maltodextrin" },
	{ key: "158", value: "Vanilla Extract" },
	{ key: "159", value: "Almond Extract" },
	{ key: "160", value: "Soy Lecithin" },

	// Dairy and Dairy Alternatives
	{ key: "161", value: "Cow's Milk" },
	{ key: "162", value: "Goat's Milk" },
	{ key: "163", value: "Soy Milk" },
	{ key: "164", value: "Almond Milk" },
	{ key: "165", value: "Oat Milk" },
	{ key: "166", value: "Coconut Milk" },
	{ key: "167", value: "Rice Milk" },
	{ key: "168", value: "Cashew Milk" },
	{ key: "169", value: "Hemp Milk" },
	{ key: "170", value: "Lactose-Free Milk" },
	{ key: "171", value: "Evaporated Milk" },
	{ key: "172", value: "Condensed Milk" },
];

export const mainIngredients = [
	{ key: "1", value: "Chicken" },
	{ key: "2", value: "Beef" },
	{ key: "3", value: "Pork" },
	{ key: "4", value: "Fish" },
	{ key: "5", value: "Shrimp" },
	{ key: "6", value: "Eggs" },
	{ key: "7", value: "Milk" },
	{ key: "8", value: "Cheese" },
	{ key: "9", value: "Butter" },
	{ key: "10", value: "Tofu" },
	{ key: "11", value: "Tempeh" },
	{ key: "12", value: "Lentils" },
	{ key: "13", value: "Chickpeas" },
	{ key: "14", value: "Beans" },
	{ key: "15", value: "Rice" },
	{ key: "16", value: "Pasta" },
	{ key: "17", value: "Potatoes" },
	{ key: "18", value: "Tomatoes" },
	{ key: "19", value: "Carrots" },
	{ key: "20", value: "Broccoli" },
	{ key: "21", value: "Cauliflower" },
	{ key: "22", value: "Peas" },
	{ key: "23", value: "Corn" },
	{ key: "24", value: "Zucchini" },
	{ key: "25", value: "Spinach" },
	{ key: "26", value: "Mushrooms" },
	{ key: "27", value: "Bell Peppers" },
	{ key: "28", value: "Avocado" },
	{ key: "29", value: "Onions" },
	{ key: "30", value: "Garlic" },
	{ key: "31", value: "Olive Oil" },
	{ key: "32", value: "Bread" },
	{ key: "33", value: "Quinoa" },
	{ key: "34", value: "Couscous" },
	{ key: "35", value: "Lamb" },
	{ key: "36", value: "Turkey" },
	{ key: "37", value: "Salmon" },
	{ key: "38", value: "Tuna" },
	{ key: "39", value: "Oats" },
	{ key: "40", value: "Flour" },
	{ key: "41", value: "Yogurt" },
	{ key: "42", value: "Coconut Milk" },
	{ key: "43", value: "Almonds" },
	{ key: "44", value: "Peanuts" },
	{ key: "45", value: "Cashews" },
	{ key: "46", value: "Walnuts" },
	{ key: "47", value: "Pumpkin" },
	{ key: "48", value: "Cabbage" },
	{ key: "49", value: "Lettuce" },
	{ key: "50", value: "Cucumber" },
	{ key: "51", value: "Beets" },
	{ key: "52", value: "Sweet Potatoes" },
	{ key: "53", value: "Apples" },
	{ key: "54", value: "Bananas" },
	{ key: "55", value: "Oranges" },
	{ key: "56", value: "Strawberries" },
	{ key: "57", value: "Blueberries" },
	{ key: "58", value: "Grapes" },
	{ key: "59", value: "Pineapple" },
	{ key: "60", value: "Mango" },
	{ key: "61", value: "Cherries" },
	{ key: "62", value: "Pears" },
];
