export const seasonings = [
	{ key: "1", value: "Salt" },
	{ key: "2", value: "Black Pepper" },
	{ key: "3", value: "Paprika" },
	{ key: "4", value: "Garlic Powder" },
	{ key: "5", value: "Onion Powder" },
	{ key: "6", value: "Cayenne Pepper" },
	{ key: "7", value: "Cumin" },
	{ key: "8", value: "Chili Powder" },
	{ key: "9", value: "Turmeric" },
	{ key: "10", value: "Coriander" },
	{ key: "11", value: "Ground Mustard" },
	{ key: "12", value: "Cinnamon" },
	{ key: "13", value: "Nutmeg" },
	{ key: "14", value: "Cloves" },
	{ key: "15", value: "Ginger Powder" },
	{ key: "16", value: "Oregano" },
	{ key: "17", value: "Thyme" },
	{ key: "18", value: "Rosemary" },
	{ key: "19", value: "Basil" },
	{ key: "20", value: "Bay Leaves" },
	{ key: "21", value: "Parsley" },
	{ key: "22", value: "Dill" },
	{ key: "23", value: "Tarragon" },
	{ key: "24", value: "Fennel Seeds" },
	{ key: "25", value: "Star Anise" },
	{ key: "26", value: "Fenugreek" },
	{ key: "27", value: "Saffron" },
	{ key: "28", value: "Cardamom" },
	{ key: "29", value: "Allspice" },
	{ key: "30", value: "Curry Powder" },
	{ key: "31", value: "Italian Seasoning" },
	{ key: "32", value: "Herbes de Provence" },
	{ key: "33", value: "Smoked Paprika" },
	{ key: "34", value: "White Pepper" },
	{ key: "35", value: "Celery Salt" },
	{ key: "36", value: "Lemon Pepper" },
	{ key: "37", value: "Sumac" },
	{ key: "38", value: "Za'atar" },
	{ key: "39", value: "Sichuan Peppercorns" },
	{ key: "40", value: "Five-Spice Powder" },
	{ key: "41", value: "Chili Flakes" },
	{ key: "42", value: "Vanilla Bean" },
	{ key: "43", value: "Sesame Seeds" },
	{ key: "44", value: "Poppy Seeds" },
	{ key: "45", value: "Nigella Seeds" },
	{ key: "46", value: "Cumin Seeds" },
	{ key: "47", value: "Caraway Seeds" },
	{ key: "48", value: "Mustard Seeds" },
	{ key: "49", value: "Ground Cloves" },
	{ key: "50", value: "Tumeric" },
	{ key: "51", value: "Ground Mace" },
	{ key: "52", value: "Fenugreek Seeds" },
	{ key: "53", value: "Curry Leaves" },
	{ key: "54", value: "Galangal" },
	{ key: "55", value: "Garlic Salt" },
	{ key: "56", value: "Lime Zest" },
	{ key: "57", value: "Orange Zest" },
	{ key: "58", value: "Lavender" },
	{ key: "59", value: "Marjoram" },
	{ key: "60", value: "Sage" },
	{ key: "61", value: "Chervil" },
	{ key: "62", value: "Tamarind" },
];

export const mainIngredients = [
	{ key: "1", value: "Chicken" },
	{ key: "2", value: "Beef" },
	{ key: "3", value: "Pork" },
	{ key: "4", value: "Fish" },
	{ key: "5", value: "Shrimp" },
	{ key: "6", value: "Eggs" },
	{ key: "7", value: "Milk" },
	{ key: "8", value: "Cheese" },
	{ key: "9", value: "Butter" },
	{ key: "10", value: "Tofu" },
	{ key: "11", value: "Tempeh" },
	{ key: "12", value: "Lentils" },
	{ key: "13", value: "Chickpeas" },
	{ key: "14", value: "Beans" },
	{ key: "15", value: "Rice" },
	{ key: "16", value: "Pasta" },
	{ key: "17", value: "Potatoes" },
	{ key: "18", value: "Tomatoes" },
	{ key: "19", value: "Carrots" },
	{ key: "20", value: "Broccoli" },
	{ key: "21", value: "Cauliflower" },
	{ key: "22", value: "Peas" },
	{ key: "23", value: "Corn" },
	{ key: "24", value: "Zucchini" },
	{ key: "25", value: "Spinach" },
	{ key: "26", value: "Mushrooms" },
	{ key: "27", value: "Bell Peppers" },
	{ key: "28", value: "Avocado" },
	{ key: "29", value: "Onions" },
	{ key: "30", value: "Garlic" },
	{ key: "31", value: "Olive Oil" },
	{ key: "32", value: "Bread" },
	{ key: "33", value: "Quinoa" },
	{ key: "34", value: "Couscous" },
	{ key: "35", value: "Lamb" },
	{ key: "36", value: "Turkey" },
	{ key: "37", value: "Salmon" },
	{ key: "38", value: "Tuna" },
	{ key: "39", value: "Oats" },
	{ key: "40", value: "Flour" },
	{ key: "41", value: "Yogurt" },
	{ key: "42", value: "Coconut Milk" },
	{ key: "43", value: "Almonds" },
	{ key: "44", value: "Peanuts" },
	{ key: "45", value: "Cashews" },
	{ key: "46", value: "Walnuts" },
	{ key: "47", value: "Pumpkin" },
	{ key: "48", value: "Cabbage" },
	{ key: "49", value: "Lettuce" },
	{ key: "50", value: "Cucumber" },
	{ key: "51", value: "Beets" },
	{ key: "52", value: "Sweet Potatoes" },
	{ key: "53", value: "Apples" },
	{ key: "54", value: "Bananas" },
	{ key: "55", value: "Oranges" },
	{ key: "56", value: "Strawberries" },
	{ key: "57", value: "Blueberries" },
	{ key: "58", value: "Grapes" },
	{ key: "59", value: "Pineapple" },
	{ key: "60", value: "Mango" },
	{ key: "61", value: "Cherries" },
	{ key: "62", value: "Pears" },
];
